---
- name: Update All Packages on CentOS Servers
  hosts: all
  become: yes  # Use become to execute tasks with sudo or as root
  gather_facts: false
  tasks:   
    - name: Update All Packages
      yum:
        name: '*'
        state: latest
      tags: [package_update]
