---
- name: Update All Packages on CentOS Servers
  hosts: targetplayground
  become: yes  # Use become to execute tasks with sudo or as root
  gather_facts: false
  tasks:
    - name: Set sudo password
      set_fact:
        ansible_become_pass: labuser
        
    - name: Update All Packages
      yum:
        name: '*'
        state: latest
      tags: [package_update]
