---
- name: Install LAMP Stack
  hosts: dbservers
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Install PHP
      package:
        name: php
        state: present

    - name: Install PHP modules
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - php-mysqlnd  # Use php-mysqlnd instead of php-mysql
        - php-xml
        - php-json
        - php-gd
        - php-mbstring
        - php-curl

    - name: Restart Apache
      service:
        name: httpd
        state: restarted

    - name: Install MySQL (MariaDB)
      package:
        name: mariadb-server
        state: present

    - name: Start and enable MySQL
      service:
        name: mariadb
        state: started
        enabled: yes
    
    - name: Run mysql_secure_installation
      expect:
        command: /usr/bin/mysql_secure_installation
        responses:
          (?i)Enter current password for root (enter for none):: "r00t.local!"
          "Change the root password? [Y/n]": "n"
          "Remove anonymous users? [Y/n]": "y"
          "Disallow root login remotely? [Y/n]": "n"
          "Remove test database and access to it? [Y/n]": "n"
          "Reload privilege tables now? [Y/n]": "y"
      register: mysql_secure_output
