---
- name: Ensure SSH Key Pair for testuser and Copy Public Key to Target Hosts
  hosts: localhost  # Run on the control machine
  gather_facts: false  # Disable gathering facts
  vars:
    testuser: "testuser"  # Set the target username
    ssh_key_private_path: "/home/{{ testuser }}/.ssh/id_rsa"
    ssh_key_public_path: "/home/{{ testuser }}/.ssh/id_rsa.pub"

  tasks:
    - name: Check if SSH private key exists
      stat:
        path: "{{ ssh_key_private_path }}"
      register: ssh_key_private_stat
      become: yes
      become_user: "{{ testuser }}"

    - name: Check if SSH public key exists
      stat:
        path: "{{ ssh_key_public_path }}"
      register: ssh_key_public_stat
      become: yes
      become_user: "{{ testuser }}"

    - name: Generate SSH Key Pair for testuser if it doesn't exist
      command: ssh-keygen -t rsa -b 4096 -f "{{ ssh_key_private_path }}" -N "" -q
      when: ssh_key_private_stat.stat.exists == false
      become: yes
      become_user: "{{ testuser }}"
      register: keygen_output

    - name: Display SSH Public Key
      debug:
        var: keygen_output.stdout_lines
      when: ssh_key_private_stat.stat.exists == false

- name: Copy SSH Public Key to Target Hosts
  hosts: targetplayground  # Provide the target hosts from your inventory file
  gather_facts: true
  vars:
    testuser: "testuser"  # Set the target username
    ssh_key_public_path: "/home/{{ testuser }}/.ssh/id_rsa.pub"
  tasks:
    - name: Copy SSH Public Key to Target Hosts
      authorized_key:
        user: "{{ testuser }}"
        key: "{{ lookup('file', ssh_key_public_path) }}"